//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.App_LocalResources.PageTitle.PageTitle", typeof(PageTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Administrative Units.
        /// </summary>
        public static string AdministrativeUnits_Add {
            get {
                return ResourceManager.GetString("AdministrativeUnits_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Administrative Units.
        /// </summary>
        public static string AdministrativeUnits_Edit {
            get {
                return ResourceManager.GetString("AdministrativeUnits_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Units.
        /// </summary>
        public static string AdministrativeUnits_Index {
            get {
                return ResourceManager.GetString("AdministrativeUnits_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Certificates And Award.
        /// </summary>
        public static string CertificatesAndAward_Add {
            get {
                return ResourceManager.GetString("CertificatesAndAward_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Certificates And Award.
        /// </summary>
        public static string CertificatesAndAward_Edit {
            get {
                return ResourceManager.GetString("CertificatesAndAward_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates And Award.
        /// </summary>
        public static string CertificatesAndAward_Index {
            get {
                return ResourceManager.GetString("CertificatesAndAward_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Course.
        /// </summary>
        public static string Course_Add {
            get {
                return ResourceManager.GetString("Course_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Course.
        /// </summary>
        public static string Course_Edit {
            get {
                return ResourceManager.GetString("Course_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course_Index {
            get {
                return ResourceManager.GetString("Course_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Direct Responsible.
        /// </summary>
        public static string DirectResponsible_Edit {
            get {
                return ResourceManager.GetString("DirectResponsible_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Responsible.
        /// </summary>
        public static string DirectResponsible_Index {
            get {
                return ResourceManager.GetString("DirectResponsible_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Educational Units.
        /// </summary>
        public static string EducationalUnits_Add {
            get {
                return ResourceManager.GetString("EducationalUnits_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Educational Units.
        /// </summary>
        public static string EducationalUnits_Edit {
            get {
                return ResourceManager.GetString("EducationalUnits_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Units.
        /// </summary>
        public static string EducationalUnits_Index {
            get {
                return ResourceManager.GetString("EducationalUnits_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Units.
        /// </summary>
        public static string EducationalUnits_Index1 {
            get {
                return ResourceManager.GetString("EducationalUnits_Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Enterprise Units.
        /// </summary>
        public static string EnterpriseUnits {
            get {
                return ResourceManager.GetString("EnterpriseUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Standard.
        /// </summary>
        public static string Evidence_Add {
            get {
                return ResourceManager.GetString("Evidence_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Standard.
        /// </summary>
        public static string Evidence_Edit {
            get {
                return ResourceManager.GetString("Evidence_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence.
        /// </summary>
        public static string Evidence_Index {
            get {
                return ResourceManager.GetString("Evidence_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators Panel.
        /// </summary>
        public static string IndicatorsPanel {
            get {
                return ResourceManager.GetString("IndicatorsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item and standards.
        /// </summary>
        public static string Item_Index {
            get {
                return ResourceManager.GetString("Item_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job Title.
        /// </summary>
        public static string JobTitle_Add {
            get {
                return ResourceManager.GetString("JobTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job Title.
        /// </summary>
        public static string JobTitle_Edit {
            get {
                return ResourceManager.GetString("JobTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Job Titles.
        /// </summary>
        public static string JobTitle_Index {
            get {
                return ResourceManager.GetString("JobTitle_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Management.
        /// </summary>
        public static string LanguageManagement {
            get {
                return ResourceManager.GetString("LanguageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level 1.
        /// </summary>
        public static string Level1_Add {
            get {
                return ResourceManager.GetString("Level1_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Level 1.
        /// </summary>
        public static string Level1_Edit {
            get {
                return ResourceManager.GetString("Level1_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Level 1.
        /// </summary>
        public static string Level1_Index {
            get {
                return ResourceManager.GetString("Level1_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level 2.
        /// </summary>
        public static string Level2_Add {
            get {
                return ResourceManager.GetString("Level2_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Level 2.
        /// </summary>
        public static string Level2_Edit {
            get {
                return ResourceManager.GetString("Level2_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Level 2.
        /// </summary>
        public static string Level2_Index {
            get {
                return ResourceManager.GetString("Level2_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level 3.
        /// </summary>
        public static string Level3_Add {
            get {
                return ResourceManager.GetString("Level3_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Level 3.
        /// </summary>
        public static string Level3_Edit {
            get {
                return ResourceManager.GetString("Level3_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Level 3.
        /// </summary>
        public static string Level3_Index {
            get {
                return ResourceManager.GetString("Level3_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level 4.
        /// </summary>
        public static string Level4_Add {
            get {
                return ResourceManager.GetString("Level4_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Level 4.
        /// </summary>
        public static string Level4_Edit {
            get {
                return ResourceManager.GetString("Level4_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Level 4.
        /// </summary>
        public static string Level4_Index {
            get {
                return ResourceManager.GetString("Level4_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Indicators Panel.
        /// </summary>
        public static string MainIndicators_Index {
            get {
                return ResourceManager.GetString("MainIndicators_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My Information.
        /// </summary>
        public static string MyInfo_Edit {
            get {
                return ResourceManager.GetString("MyInfo_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        public static string MyInfo_Index {
            get {
                return ResourceManager.GetString("MyInfo_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stage Performance.
        /// </summary>
        public static string MyPerformance_Index {
            get {
                return ResourceManager.GetString("MyPerformance_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations Management.
        /// </summary>
        public static string OrganizationsManagement {
            get {
                return ResourceManager.GetString("OrganizationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privelages.
        /// </summary>
        public static string Privelages {
            get {
                return ResourceManager.GetString("Privelages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Privelages.
        /// </summary>
        public static string Privelages_Add {
            get {
                return ResourceManager.GetString("Privelages_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Qualification.
        /// </summary>
        public static string Qualification_Add {
            get {
                return ResourceManager.GetString("Qualification_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Qualification.
        /// </summary>
        public static string Qualification_Edit {
            get {
                return ResourceManager.GetString("Qualification_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Qualification_Index {
            get {
                return ResourceManager.GetString("Qualification_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Standard.
        /// </summary>
        public static string Standard_Add {
            get {
                return ResourceManager.GetString("Standard_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Standard.
        /// </summary>
        public static string Standard_Edit {
            get {
                return ResourceManager.GetString("Standard_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard_Index {
            get {
                return ResourceManager.GetString("Standard_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Indicators Panel.
        /// </summary>
        public static string SubIndicatorsPanel_Index {
            get {
                return ResourceManager.GetString("SubIndicatorsPanel_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administration.
        /// </summary>
        public static string SystemAdministration {
            get {
                return ResourceManager.GetString("SystemAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string User_Add {
            get {
                return ResourceManager.GetString("User_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string User_Edit {
            get {
                return ResourceManager.GetString("User_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string User_Index {
            get {
                return ResourceManager.GetString("User_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Category.
        /// </summary>
        public static string UserCategory_Add {
            get {
                return ResourceManager.GetString("UserCategory_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Category.
        /// </summary>
        public static string UserCategory_Edit {
            get {
                return ResourceManager.GetString("UserCategory_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Category.
        /// </summary>
        public static string UserCategory_Index {
            get {
                return ResourceManager.GetString("UserCategory_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string UserInfo_Certificates {
            get {
                return ResourceManager.GetString("UserInfo_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string UserInfo_Courses {
            get {
                return ResourceManager.GetString("UserInfo_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        public static string UserInfo_MyInfo {
            get {
                return ResourceManager.GetString("UserInfo_MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string UserInfo_Qualifications {
            get {
                return ResourceManager.GetString("UserInfo_Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Managment.
        /// </summary>
        public static string UserManagment {
            get {
                return ResourceManager.GetString("UserManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Units.
        /// </summary>
        public static string UserUnit {
            get {
                return ResourceManager.GetString("UserUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Planning.
        /// </summary>
        public static string WorkPlanning {
            get {
                return ResourceManager.GetString("WorkPlanning", resourceCulture);
            }
        }
    }
}
