//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActEntities : DbContext
    {
        public ActEntities()
            : base("name=ActEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Level1> Level1 { get; set; }
        public virtual DbSet<Level2> Level2 { get; set; }
        public virtual DbSet<Level3> Level3 { get; set; }
        public virtual DbSet<Level4> Level4 { get; set; }
        public virtual DbSet<CientificDegree> CientificDegrees { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<SchoolType> SchoolTypes { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<TypeEducation> TypeEducations { get; set; }
        public virtual DbSet<MenuPrivelag> MenuPrivelags { get; set; }
        public virtual DbSet<Evidence> Evidences { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemNACategory> ItemNACategories { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Standard> Standards { get; set; }
        public virtual DbSet<UserCategory> UserCategories { get; set; }
        public virtual DbSet<CertificatesAndAward> CertificatesAndAwards { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<UnitUser> UnitUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<EnterpriseUnit> EnterpriseUnits { get; set; }
        public virtual DbSet<SubIndicatorsCategory> SubIndicatorsCategories { get; set; }
        public virtual DbSet<vw_All_Level> vw_All_Level { get; set; }
    }
}
