//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnterpriseUnit()
        {
            this.UnitUsers = new HashSet<UnitUser>();
            this.EnterpriseUnits1 = new HashSet<EnterpriseUnit>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> Parent { get; set; }
        public short EnterpriseUnitsType { get; set; }
        public Nullable<decimal> Level1Id { get; set; }
        public Nullable<decimal> Level2Id { get; set; }
        public Nullable<decimal> Level3Id { get; set; }
        public Nullable<decimal> Level4Id { get; set; }
        public string Name { get; set; }
        public decimal DisplayOrder { get; set; }
        public decimal CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Level1 Level1 { get; set; }
        public virtual Level2 Level2 { get; set; }
        public virtual Level3 Level3 { get; set; }
        public virtual Level4 Level4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitUser> UnitUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseUnit> EnterpriseUnits1 { get; set; }
        public virtual EnterpriseUnit EnterpriseUnit1 { get; set; }
        public virtual EnterpriseUnit EnterpriseUnits11 { get; set; }
        public virtual EnterpriseUnit EnterpriseUnit2 { get; set; }
    }
}
