//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidence
    {
        public decimal Id { get; set; }
        public decimal StandardId { get; set; }
        public string EvidenceDescription { get; set; }
        public decimal CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public decimal DisplayOrder { get; set; }
    
        public virtual Standard Standard { get; set; }
    }
}
