//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemNACategories = new HashSet<ItemNACategory>();
            this.Standards = new HashSet<Standard>();
            this.SubIndicatorsCategories = new HashSet<SubIndicatorsCategory>();
        }
    
        public decimal Id { get; set; }
        public decimal SectorId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Goal { get; set; }
        public string ShortGoal { get; set; }
        public Nullable<decimal> FixedWeight { get; set; }
        public Nullable<decimal> IntermediateWeight { get; set; }
        public Nullable<decimal> FlexWeight { get; set; }
        public decimal DisplayOrder { get; set; }
        public decimal Publish { get; set; }
    
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemNACategory> ItemNACategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standard> Standards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubIndicatorsCategory> SubIndicatorsCategories { get; set; }
    }
}
