//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobTitle()
        {
            this.MenuPrivelags = new HashSet<MenuPrivelag>();
            this.Users = new HashSet<User>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> Level1Id { get; set; }
        public Nullable<decimal> Level2Id { get; set; }
        public Nullable<decimal> Level3Id { get; set; }
        public Nullable<decimal> Level4Id { get; set; }
        public decimal UserCategoryId { get; set; }
        public string JobName { get; set; }
        public decimal DisplayOrder { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Level1 Level1 { get; set; }
        public virtual Level2 Level2 { get; set; }
        public virtual Level3 Level3 { get; set; }
        public virtual Level4 Level4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPrivelag> MenuPrivelags { get; set; }
        public virtual UserCategory UserCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
