//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPrivelag
    {
        public decimal Id { get; set; }
        public int MenuId { get; set; }
        public Nullable<decimal> JobTitleId { get; set; }
        public Nullable<decimal> CategoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal CretaedBy { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
