//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public decimal Id { get; set; }
        public decimal ScientificDegreeId { get; set; }
        public string Specialization { get; set; }
        public string University { get; set; }
        public int Year { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CientificDegree CientificDegree { get; set; }
        public virtual User User { get; set; }
    }
}
