//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standard()
        {
            this.Evidences = new HashSet<Evidence>();
            this.SubIndicatorsCategories = new HashSet<SubIndicatorsCategory>();
        }
    
        public decimal Id { get; set; }
        public decimal ItemId { get; set; }
        public decimal CategoryId { get; set; }
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public decimal CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public decimal DisplayOrder { get; set; }
        public bool Publish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidence> Evidences { get; set; }
        public virtual Item Item { get; set; }
        public virtual UserCategory UserCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubIndicatorsCategory> SubIndicatorsCategories { get; set; }
    }
}
