//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitUser
    {
        public decimal Id { get; set; }
        public decimal UserId { get; set; }
        public decimal UnitId { get; set; }
        public Nullable<bool> IsResponsible { get; set; }
    
        public virtual EnterpriseUnit EnterpriseUnit { get; set; }
        public virtual User User { get; set; }
    }
}
