//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_All_Level
    {
        public decimal LevelId { get; set; }
        public Nullable<decimal> Level1Id { get; set; }
        public Nullable<decimal> Level2Id { get; set; }
        public Nullable<decimal> Level3Id { get; set; }
        public Nullable<decimal> Level4Id { get; set; }
        public string LevelName { get; set; }
        public decimal DisplayOrder { get; set; }
        public Nullable<int> Published { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public Nullable<decimal> DirectResponsible { get; set; }
        public int levelNumber { get; set; }
    }
}
