//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.App_LocalResources.Common.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date obtained.
        /// </summary>
        public static string CertificatesAndAward_DateOfCertificate {
            get {
                return ResourceManager.GetString("CertificatesAndAward_DateOfCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Or Award Name.
        /// </summary>
        public static string CertificatesAndAward_Name {
            get {
                return ResourceManager.GetString("CertificatesAndAward_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its source.
        /// </summary>
        public static string CertificatesAndAward_Source {
            get {
                return ResourceManager.GetString("CertificatesAndAward_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Common_JobTitleId {
            get {
                return ResourceManager.GetString("Common_JobTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        public static string Common_Level1Id {
            get {
                return ResourceManager.GetString("Common_Level1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        public static string Common_Level2Id {
            get {
                return ResourceManager.GetString("Common_Level2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        public static string Common_Level3Id {
            get {
                return ResourceManager.GetString("Common_Level3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        public static string Common_Level4Id {
            get {
                return ResourceManager.GetString("Common_Level4Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string Common_LevelName {
            get {
                return ResourceManager.GetString("Common_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Common_User {
            get {
                return ResourceManager.GetString("Common_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Category.
        /// </summary>
        public static string Common_UserCategoryId {
            get {
                return ResourceManager.GetString("Common_UserCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Users Of Level.
        /// </summary>
        public static string CountUsersOfLevel {
            get {
                return ResourceManager.GetString("CountUsersOfLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDate.
        /// </summary>
        public static string Course_FromDate {
            get {
                return ResourceManager.GetString("Course_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to institution.
        /// </summary>
        public static string Course_institution {
            get {
                return ResourceManager.GetString("Course_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Course_Period {
            get {
                return ResourceManager.GetString("Course_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDate.
        /// </summary>
        public static string Course_ToDate {
            get {
                return ResourceManager.GetString("Course_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Course.
        /// </summary>
        public static string Course_TrainingCourse {
            get {
                return ResourceManager.GetString("Course_TrainingCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string deleteCancelButton {
            get {
                return ResourceManager.GetString("deleteCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Item Not Found.
        /// </summary>
        public static string DeletedItemNotFound {
            get {
                return ResourceManager.GetString("DeletedItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string deleteOkButton {
            get {
                return ResourceManager.GetString("deleteOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete ?.
        /// </summary>
        public static string deleteTitle {
            get {
                return ResourceManager.GetString("deleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level.
        /// </summary>
        public static string DirectResponsible_LevelName {
            get {
                return ResourceManager.GetString("DirectResponsible_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Responsible.
        /// </summary>
        public static string DirectResponsible_ResponsibleName {
            get {
                return ResourceManager.GetString("DirectResponsible_ResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select --.
        /// </summary>
        public static string DropDownnPleaseSelect {
            get {
                return ResourceManager.GetString("DropDownnPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string emptyTable {
            get {
                return ResourceManager.GetString("emptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Of Additive Users.
        /// </summary>
        public static string EnterpriseUnits_CountAdditiveUsers {
            get {
                return ResourceManager.GetString("EnterpriseUnits_CountAdditiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string EnterpriseUnits_DisplayOrder {
            get {
                return ResourceManager.GetString("EnterpriseUnits_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EnterpriseUnits_Name {
            get {
                return ResourceManager.GetString("EnterpriseUnits_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Additive Users.
        /// </summary>
        public static string EnterpriseUnits_NoAdditiveUsers {
            get {
                return ResourceManager.GetString("EnterpriseUnits_NoAdditiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Responsable User .
        /// </summary>
        public static string EnterpriseUnits_NoResponsableUser {
            get {
                return ResourceManager.GetString("EnterpriseUnits_NoResponsableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Parent.
        /// </summary>
        public static string EnterpriseUnits_Parent {
            get {
                return ResourceManager.GetString("EnterpriseUnits_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Responsible.
        /// </summary>
        public static string EnterpriseUnits_UnitResponsibleFullName {
            get {
                return ResourceManager.GetString("EnterpriseUnits_UnitResponsibleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additive Users.
        /// </summary>
        public static string EnterpriseUnits_UnitUsersFullName {
            get {
                return ResourceManager.GetString("EnterpriseUnits_UnitUsersFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string EnterpriseUnits_ViewAll {
            get {
                return ResourceManager.GetString("EnterpriseUnits_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this page.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access this screen , a special screen direct manager.
        /// </summary>
        public static string Error_AccessDenied_Manager {
            get {
                return ResourceManager.GetString("Error_AccessDenied_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is associated with other data.
        /// </summary>
        public static string Error_DeleteAssociated {
            get {
                return ResourceManager.GetString("Error_DeleteAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request ,
        ///Please Try Again later.
        /// </summary>
        public static string Error_ProcessRequest {
            get {
                return ResourceManager.GetString("Error_ProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Evidence_DisplayOrder {
            get {
                return ResourceManager.GetString("Evidence_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence.
        /// </summary>
        public static string Evidence_EvidenceDescription {
            get {
                return ResourceManager.GetString("Evidence_EvidenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GeneralClose {
            get {
                return ResourceManager.GetString("GeneralClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string GeneralOk {
            get {
                return ResourceManager.GetString("GeneralOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsStanderdWeightSumGreaterItem.
        /// </summary>
        public static string IsStanderdWeightSumGreaterItem {
            get {
                return ResourceManager.GetString("IsStanderdWeightSumGreaterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Weight.
        /// </summary>
        public static string Item_FixedWeight {
            get {
                return ResourceManager.GetString("Item_FixedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Weight.
        /// </summary>
        public static string Item_FlexWeight {
            get {
                return ResourceManager.GetString("Item_FlexWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Weight.
        /// </summary>
        public static string Item_IntermediateWeight {
            get {
                return ResourceManager.GetString("Item_IntermediateWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string Item_NA_No {
            get {
                return ResourceManager.GetString("Item_NA_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies.
        /// </summary>
        public static string Item_NA_Yes {
            get {
                return ResourceManager.GetString("Item_NA_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string Item_ShortName {
            get {
                return ResourceManager.GetString("Item_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is Na For Target Category.
        /// </summary>
        public static string ItemNaForTargetCategory {
            get {
                return ResourceManager.GetString("ItemNaForTargetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title Name.
        /// </summary>
        public static string JobTitle_Name {
            get {
                return ResourceManager.GetString("JobTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 0.
        /// </summary>
        public static string Level0 {
            get {
                return ResourceManager.GetString("Level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Level1DisplayOrder {
            get {
                return ResourceManager.GetString("Level1DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string Level1IsDefault {
            get {
                return ResourceManager.GetString("Level1IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry Name.
        /// </summary>
        public static string Level1MinistryName {
            get {
                return ResourceManager.GetString("Level1MinistryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1 Name.
        /// </summary>
        public static string Level1Name {
            get {
                return ResourceManager.GetString("Level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Level1Published {
            get {
                return ResourceManager.GetString("Level1Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code English.
        /// </summary>
        public static string Level1ThreeLetterIsoCode {
            get {
                return ResourceManager.GetString("Level1ThreeLetterIsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Level2DisplayOrder {
            get {
                return ResourceManager.GetString("Level2DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string Level2IsDefault {
            get {
                return ResourceManager.GetString("Level2IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Name.
        /// </summary>
        public static string Level2Level1 {
            get {
                return ResourceManager.GetString("Level2Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Name.
        /// </summary>
        public static string Level2Level1Name {
            get {
                return ResourceManager.GetString("Level2Level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 MinistryName.
        /// </summary>
        public static string Level2LevelMinistryName {
            get {
                return ResourceManager.GetString("Level2LevelMinistryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2 Name.
        /// </summary>
        public static string Level2Name {
            get {
                return ResourceManager.GetString("Level2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Level2Published {
            get {
                return ResourceManager.GetString("Level2Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string Level3DisplayOrder {
            get {
                return ResourceManager.GetString("Level3DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string Level3IsDefault {
            get {
                return ResourceManager.GetString("Level3IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Name.
        /// </summary>
        public static string Level3Level1 {
            get {
                return ResourceManager.GetString("Level3Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Name.
        /// </summary>
        public static string Level3Level1Name {
            get {
                return ResourceManager.GetString("Level3Level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2 Name.
        /// </summary>
        public static string Level3Level2Name {
            get {
                return ResourceManager.GetString("Level3Level2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Ministry.
        /// </summary>
        public static string Level3LevelMinistry {
            get {
                return ResourceManager.GetString("Level3LevelMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        public static string Level3LevelMinistryName {
            get {
                return ResourceManager.GetString("Level3LevelMinistryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level3  Name.
        /// </summary>
        public static string Level3Name {
            get {
                return ResourceManager.GetString("Level3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Level3Published {
            get {
                return ResourceManager.GetString("Level3Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved curricula in the  Level 4.
        /// </summary>
        public static string Level4ApprovedCurricula {
            get {
                return ResourceManager.GetString("Level4ApprovedCurricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order .
        /// </summary>
        public static string Level4DisplayOrder {
            get {
                return ResourceManager.GetString("Level4DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Basic.
        /// </summary>
        public static string Level4IsBasic {
            get {
                return ResourceManager.GetString("Level4IsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string Level4IsDefault {
            get {
                return ResourceManager.GetString("Level4IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Kindergarten.
        /// </summary>
        public static string Level4IsKindergarten {
            get {
                return ResourceManager.GetString("Level4IsKindergarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Medium.
        /// </summary>
        public static string Level4IsMedium {
            get {
                return ResourceManager.GetString("Level4IsMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ministry Education.
        /// </summary>
        public static string Level4IsMinistryEducation {
            get {
                return ResourceManager.GetString("Level4IsMinistryEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Other Education.
        /// </summary>
        public static string Level4IsOtherEducation {
            get {
                return ResourceManager.GetString("Level4IsOtherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Secondary.
        /// </summary>
        public static string Level4IsSecondary {
            get {
                return ResourceManager.GetString("Level4IsSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1.
        /// </summary>
        public static string Level4Level1 {
            get {
                return ResourceManager.GetString("Level4Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2 .
        /// </summary>
        public static string Level4Level2 {
            get {
                return ResourceManager.GetString("Level4Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level3.
        /// </summary>
        public static string Level4Level3 {
            get {
                return ResourceManager.GetString("Level4Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        public static string Level4LevelMinistry {
            get {
                return ResourceManager.GetString("Level4LevelMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level4 .
        /// </summary>
        public static string Level4Name {
            get {
                return ResourceManager.GetString("Level4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Education Name.
        /// </summary>
        public static string Level4OtherEducationName {
            get {
                return ResourceManager.GetString("Level4OtherEducationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published ?.
        /// </summary>
        public static string Level4Published {
            get {
                return ResourceManager.GetString("Level4Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages Level 4.
        /// </summary>
        public static string Level4Stages {
            get {
                return ResourceManager.GetString("Level4Stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type EducationId.
        /// </summary>
        public static string Level4TypeEducationId {
            get {
                return ResourceManager.GetString("Level4TypeEducationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeId.
        /// </summary>
        public static string Level4TypeId {
            get {
                return ResourceManager.GetString("Level4TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadingRecords.
        /// </summary>
        public static string loadingRecords {
            get {
                return ResourceManager.GetString("loadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string MyInfo_Address {
            get {
                return ResourceManager.GetString("MyInfo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Phone Number.
        /// </summary>
        public static string MyInfo_AnotherPhoneNumber {
            get {
                return ResourceManager.GetString("MyInfo_AnotherPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string MyInfo_FirstName {
            get {
                return ResourceManager.GetString("MyInfo_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string MyInfo_LastName {
            get {
                return ResourceManager.GetString("MyInfo_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string MyInfo_PhoneNumber {
            get {
                return ResourceManager.GetString("MyInfo_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string MyInfo_SecondName {
            get {
                return ResourceManager.GetString("MyInfo_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name.
        /// </summary>
        public static string MyInfo_ThirdName {
            get {
                return ResourceManager.GetString("MyInfo_ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string MyInfoReadOnly_Address {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Phone Number.
        /// </summary>
        public static string MyInfoReadOnly_AnotherPhoneNumber {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_AnotherPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MyInfoReadOnly_Email {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string MyInfoReadOnly_FirstName {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenderId.
        /// </summary>
        public static string MyInfoReadOnly_Gender {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string MyInfoReadOnly_LastName {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string MyInfoReadOnly_PhoneNumber {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string MyInfoReadOnly_SecondName {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name.
        /// </summary>
        public static string MyInfoReadOnly_ThirdName {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string MyInfoReadOnly_UserName {
            get {
                return ResourceManager.GetString("MyInfoReadOnly_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Category.
        /// </summary>
        public static string PleaseSelectCategory {
            get {
                return ResourceManager.GetString("PleaseSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Item.
        /// </summary>
        public static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Degree.
        /// </summary>
        public static string Qualification_ScientificDegreeId {
            get {
                return ResourceManager.GetString("Qualification_ScientificDegreeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Qualification_Specialization {
            get {
                return ResourceManager.GetString("Qualification_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string Qualification_University {
            get {
                return ResourceManager.GetString("Qualification_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Qualification_Year {
            get {
                return ResourceManager.GetString("Qualification_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string rtl {
            get {
                return ResourceManager.GetString("rtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOrder.
        /// </summary>
        public static string Standard_DisplayOrder {
            get {
                return ResourceManager.GetString("Standard_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidences.
        /// </summary>
        public static string Standard_Evidences {
            get {
                return ResourceManager.GetString("Standard_Evidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Name.
        /// </summary>
        public static string Standard_Name {
            get {
                return ResourceManager.GetString("Standard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Standard_Publish {
            get {
                return ResourceManager.GetString("Standard_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Standard_Weight {
            get {
                return ResourceManager.GetString("Standard_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string SubIndicators_EmptyQuantity {
            get {
                return ResourceManager.GetString("SubIndicators_EmptyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business activities and leadership recurrent and non-recurrent.
        /// </summary>
        public static string SubIndicators_Header1 {
            get {
                return ResourceManager.GetString("SubIndicators_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Continuous.
        /// </summary>
        public static string SubIndicators_IsContinuous {
            get {
                return ResourceManager.GetString("SubIndicators_IsContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Item.
        /// </summary>
        public static string SubIndicators_NextItem {
            get {
                return ResourceManager.GetString("SubIndicators_NextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no standards for this item.
        /// </summary>
        public static string SubIndicators_NoStandardsForThisItem {
            get {
                return ResourceManager.GetString("SubIndicators_NoStandardsForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Item.
        /// </summary>
        public static string SubIndicators_PreviousItem {
            get {
                return ResourceManager.GetString("SubIndicators_PreviousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string SubIndicators_Quantity {
            get {
                return ResourceManager.GetString("SubIndicators_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Categories.
        /// </summary>
        public static string SubIndicators_RelatedCategories {
            get {
                return ResourceManager.GetString("SubIndicators_RelatedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no related categories for this category.
        /// </summary>
        public static string SubIndicators_RelatedCategoriesEmpty {
            get {
                return ResourceManager.GetString("SubIndicators_RelatedCategoriesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Categories.
        /// </summary>
        public static string SubIndicators_TargetCategories {
            get {
                return ResourceManager.GetString("SubIndicators_TargetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the quantity or select the field as continuous.
        /// </summary>
        public static string SubIndicators_validationEditable {
            get {
                return ResourceManager.GetString("SubIndicators_validationEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string SubIndicators_Weight {
            get {
                return ResourceManager.GetString("SubIndicators_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Indicators For Item.
        /// </summary>
        public static string SubIndicatorsForItem {
            get {
                return ResourceManager.GetString("SubIndicatorsForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string successDelete {
            get {
                return ResourceManager.GetString("successDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string successOkButton {
            get {
                return ResourceManager.GetString("successOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Success.
        /// </summary>
        public static string successText {
            get {
                return ResourceManager.GetString("successText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string successTitle {
            get {
                return ResourceManager.GetString("successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareget Value.
        /// </summary>
        public static string TargetValue {
            get {
                return ResourceManager.GetString("TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string TotalRecord {
            get {
                return ResourceManager.GetString("TotalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exist in other unti.
        /// </summary>
        public static string UnitUser_ConfirmModalText {
            get {
                return ResourceManager.GetString("UnitUser_ConfirmModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string UnitUser_ConfirmTitle {
            get {
                return ResourceManager.GetString("UnitUser_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted  Failed.
        /// </summary>
        public static string unsuccessDelete {
            get {
                return ResourceManager.GetString("unsuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string unsuccessOkButton {
            get {
                return ResourceManager.GetString("unsuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string unsuccessText {
            get {
                return ResourceManager.GetString("unsuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string unsuccessTitle {
            get {
                return ResourceManager.GetString("unsuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string User_Active {
            get {
                return ResourceManager.GetString("User_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string User_Address {
            get {
                return ResourceManager.GetString("User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Phone Number.
        /// </summary>
        public static string User_AnotherPhoneNumber {
            get {
                return ResourceManager.GetString("User_AnotherPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English First Name.
        /// </summary>
        public static string User_FirstNameEn {
            get {
                return ResourceManager.GetString("User_FirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenderId.
        /// </summary>
        public static string User_GenderId {
            get {
                return ResourceManager.GetString("User_GenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title .
        /// </summary>
        public static string User_JobTitleName {
            get {
                return ResourceManager.GetString("User_JobTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Last Name.
        /// </summary>
        public static string User_LastNameEn {
            get {
                return ResourceManager.GetString("User_LastNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string User_SecondName {
            get {
                return ResourceManager.GetString("User_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name.
        /// </summary>
        public static string User_ThirdName {
            get {
                return ResourceManager.GetString("User_ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Category.
        /// </summary>
        public static string User_UserCategoryName {
            get {
                return ResourceManager.GetString("User_UserCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string UserCategory_Active {
            get {
                return ResourceManager.GetString("UserCategory_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string UserCategory_DisplayOrder {
            get {
                return ResourceManager.GetString("UserCategory_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        public static string UserCategory_Level1Id {
            get {
                return ResourceManager.GetString("UserCategory_Level1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        public static string UserCategory_Level2Id {
            get {
                return ResourceManager.GetString("UserCategory_Level2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        public static string UserCategory_Level3Id {
            get {
                return ResourceManager.GetString("UserCategory_Level3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        public static string UserCategory_Level4Id {
            get {
                return ResourceManager.GetString("UserCategory_Level4Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string UserCategory_LevelName {
            get {
                return ResourceManager.GetString("UserCategory_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string UserCategory_Name {
            get {
                return ResourceManager.GetString("UserCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category System Name.
        /// </summary>
        public static string UserCategory_SystemName {
            get {
                return ResourceManager.GetString("UserCategory_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string UserCategory_Type {
            get {
                return ResourceManager.GetString("UserCategory_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a category for system administrators that cannot be deleted.
        /// </summary>
        public static string UserCategory_Validation_IsSystemAdmin {
            get {
                return ResourceManager.GetString("UserCategory_Validation_IsSystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string UserUnits_Added {
            get {
                return ResourceManager.GetString("UserUnits_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Added.
        /// </summary>
        public static string UserUnits_NotAdded {
            get {
                return ResourceManager.GetString("UserUnits_NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Responsable.
        /// </summary>
        public static string UserUnits_Responsable {
            get {
                return ResourceManager.GetString("UserUnits_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only English characters.
        /// </summary>
        public static string Validation_EnglishChar {
            get {
                return ResourceManager.GetString("Validation_EnglishChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is already exists.
        /// </summary>
        public static string Validation_IsExists {
            get {
                return ResourceManager.GetString("Validation_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is number only.
        /// </summary>
        public static string Validation_Number {
            get {
                return ResourceManager.GetString("Validation_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length  is {1} characters.
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ViewCategoryAndItem_CategoryName {
            get {
                return ResourceManager.GetString("ViewCategoryAndItem_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ViewCategoryAndItem_ItemName {
            get {
                return ResourceManager.GetString("ViewCategoryAndItem_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ViewCategoryAndItemStandard_CategoryName {
            get {
                return ResourceManager.GetString("ViewCategoryAndItemStandard_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ViewCategoryAndItemStandard_ItemName {
            get {
                return ResourceManager.GetString("ViewCategoryAndItemStandard_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ViewCategoryAndItemStandard_StandardName {
            get {
                return ResourceManager.GetString("ViewCategoryAndItemStandard_StandardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Responsible.
        /// </summary>
        public static string WithoutResponsible {
            get {
                return ResourceManager.GetString("WithoutResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zeroRecords.
        /// </summary>
        public static string zeroRecords {
            get {
                return ResourceManager.GetString("zeroRecords", resourceCulture);
            }
        }
    }
}
